In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(r"C:\Users\sello\Downloads\Attrition Dataset.csv")

df.head()

,employee_id,department,role_level,tenure_years,salary_band,performance_rating,training_hours_annual,avg_overtime_hrs_week,job_satisfaction_score,work_life_balance_score,last_promotion_years_ago,attrition_flag,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,EMP-0009731,Sales,Individual Contributor,8.3,Band 1,4.9,50,23.1,2.4,3.1,0.1,0,NaN,NaN,NaN
1,EMP-0008311,Finance,VP,16.0,Band 6,2.3,101,8.5,5.0,1.0,3.2,0,NaN,NaN,NaN
2,EMP-0003986,Operations,Associate,26.2,Band 1,1.6,98,5.7,4.4,3.7,1.6,0,NaN,NaN,NaN
3,EMP-0003056,Engineering,Individual Contributor,28.4,Band 3,4.9,35,1.6,3.9,3.3,8.8,0,NaN,NaN,NaN
4,EMP-0014424,Product,Manager,3.9,Band 1,3.4,8,18.2,3.1,3.2,7.0,1,NaN,NaN,NaN

In [6]:
df.shape

(15000, 15)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 15 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   employee_id               15000 non-null  str
 1   department                15000 non-null  str
 2   role_level                15000 non-null  str
 3   tenure_years              15000 non-null  float64
 4   salary_band               15000 non-null  str
 5   performance_rating        15000 non-null  float64
 6   training_hours_annual     15000 non-null  int64
 7   avg_overtime_hrs_week     15000 non-null  float64
 8   job_satisfaction_score    15000 non-null  float64
 9   work_life_balance_score   15000 non-null  float64
 10  last_promotion_years_ago  15000 non-null  float64
 11  attrition_flag            15000 non-null  int64
 12  Unnamed: 12               0 non-null      float64
 13  Unnamed: 13               0 non-null      float64
 14  Unnamed: 14               0 non-null      float64
dtypes: float64(9), int64(2), str(4)
memory usage: 1.7 MB

In [10]:
df.isnull().sum()

employee_id                     0
department                      0
role_level                      0
tenure_years                    0
salary_band                     0
performance_rating              0
training_hours_annual           0
avg_overtime_hrs_week           0
job_satisfaction_score          0
work_life_balance_score         0
last_promotion_years_ago        0
attrition_flag                  0
Unnamed: 12                 15000
Unnamed: 13                 15000
Unnamed: 14                 15000
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["attrition_flag"].value_counts()

attrition_flag
0    11203
1     3797
Name: count, dtype: int64

In [16]:
round(df["attrition_flag"].value_counts(normalize=True)*100,2)

attrition_flag
0    74.69
1    25.31
Name: proportion, dtype: float64

In [18]:
df.groupby("department")["attrition_flag"].value_counts()

department        attrition_flag
Customer Success  0                 1083
                  1                  430
Engineering       0                 1156
                  1                  401
Finance           0                 1099
                  1                  365
HR                0                 1133
                  1                  365
IT                0                 1138
                  1                  364
Legal             0                 1088
                  1                  371
Marketing         0                 1085
                  1                  383
Operations        0                 1119
                  1                  390
Product           0                 1136
                  1                  373
Sales             0                 1166
                  1                  355
Name: count, dtype: int64

In [20]:
pd.crosstab(df["avg_overtime_hrs_week"],df["attrition_flag"])

attrition_flag          0   1
avg_overtime_hrs_week
0.0                    23  13
0.1                    48  10
0.2                    60  13
0.3                    50  24
0.4                    62  13
...                    ..  ..
24.6                   38  13
24.7                   39  17
24.8                   51  21
24.9                   26  23
25.0                   21  11

[251 rows x 2 columns]

In [23]:
pd.crosstab(df["work_life_balance_score"],df["attrition_flag"])

attrition_flag             0    1
work_life_balance_score
1.0                      285   91
1.1                       75   26
1.2                       82   34
1.3                      101   45
1.4                      128   52
1.5                      148   50
1.6                      146   61
1.7                      187   58
1.8                      229   71
1.9                      270   89
2.0                      283  100
2.1                      323   95
2.2                      328  108
2.3                      375  123
2.4                      375  113
2.5                      388  122
2.6                      414  147
2.7                      438  152
2.8                      431  132
2.9                      431  152
3.0                      500  142
3.1                      412  150
3.2                      433  145
3.3                      401  145
3.4                      381  137
3.5                      370  142
3.6                      392  135
3.7                      337  122
3.8                      310  123
3.9                      287  102
4.0                      276   90
4.1                      250   75
4.2                      219   62
4.3                      194   62
4.4                      171   54
4.5                      141   63
4.6                      134   48
4.7                      115   37
4.8                       73   32
4.9                       86   13
5.0                      284   97

In [24]:
pd.crosstab(df["last_promotion_years_ago"],df["attrition_flag"])

attrition_flag              0   1
last_promotion_years_ago
0.0                        59  16
0.1                       119  32
0.2                       125  35
0.3                       130  32
0.4                       114  40
...                       ...  ..
9.6                       102  37
9.7                       110  46
9.8                       112  45
9.9                       102  35
10.0                       56  26

[101 rows x 2 columns]